/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphic;

import Data.Objects;
import Data.Parameters;
import Logic.Tables;
import Logic.Windows;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author krosales
 */
public class Historial extends javax.swing.JFrame {

    /**
     * Creates new form Historial
     */
    public Historial() {
        initComponents();
         Tables.TablaHistorial.addColumn("FACTURA");
         Tables.TablaHistorial.addColumn("NOMBRE");
         Tables.TablaHistorial.addColumn("DIRECCION");
         Tables.TablaHistorial.addColumn("NIT");
         Tables.TablaHistorial.addColumn("TOTAL");
         TablaHistorial.setModel(Tables.TablaHistorial);
        TablaHistorial.getColumnModel().getColumn(0).setPreferredWidth(40);
        TablaHistorial.getColumnModel().getColumn(1).setPreferredWidth(80);
        TablaHistorial.getColumnModel().getColumn(2).setPreferredWidth(400);
        TablaHistorial.getColumnModel().getColumn(3).setPreferredWidth(80);
        TablaHistorial.getColumnModel().getColumn(3).setPreferredWidth(40);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaHistorial = new RSMaterialComponent.RSTableMetro();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        TablaHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaHistorial.setBackgoundHead(new java.awt.Color(Parameters.ColorApp1, Parameters.ColorApp2, Parameters.ColorApp3));
        TablaHistorial.setBackgoundHover(new java.awt.Color(0, 0, 0));
        TablaHistorial.setColorPrimaryText(new java.awt.Color(0, 0, 0));
        TablaHistorial.setColorSecondary(new java.awt.Color(255, 255, 255));
        TablaHistorial.setColorSecundaryText(new java.awt.Color(0, 0, 0));
        TablaHistorial.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        TablaHistorial.setFontHead(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        TablaHistorial.setFontRowSelect(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        TablaHistorial.setGridColor(new java.awt.Color(0, 0, 0));
        TablaHistorial.setHighHead(30);
        TablaHistorial.setRowHeight(30);
        TablaHistorial.setSelectionBackground(new java.awt.Color(0, 0, 0));
        TablaHistorial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TablaHistorialKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(TablaHistorial);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("HISTORIAL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1000, 312));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TablaHistorialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TablaHistorialKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            Windows.Historial.setVisible(false);
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int val = JOptionPane.showConfirmDialog(null, "¿DESEA HACER REIMPRESION?");
            if (val == 0) {
                Objects.Methods.SetPlantilla(TablaHistorial, true);
            }
            if (val != 0) {
                int val2 = JOptionPane.showConfirmDialog(null, "¿HACER NUEVA FACTURA CON ESTOS DATOS?");
                if (val2 == 0) {
                    Objects.Methods.SetPlantilla(TablaHistorial, false);
                }
            }
        }

    }//GEN-LAST:event_TablaHistorialKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Historial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static RSMaterialComponent.RSTableMetro TablaHistorial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
