/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphic;

import Data.Objects;
import Data.Parameters;
import Logic.Windows;
import java.awt.event.KeyEvent;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import necesario.RSFileChooser;

/**
 *
 * @author Kev
 */
public class Settings extends javax.swing.JFrame {

    RSFileChooser selecArchivo = new RSFileChooser();
    File archivo;
    int contAccion = 0;

    public Settings() {
        initComponents();
        this.setTitle("DATA BASE");
        setIconImage(new ImageIcon(getClass().getResource("/Resources/" + Parameters.IconoDB + ".png")).getImage());
        Mensaje.setVisible(false);
        PanelTabla.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rSButtonIcon_new1 = new newscomponents.RSButtonIcon_new();
        Mensaje = new javax.swing.JLabel();
        PanelTabla = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaExcel = new rojerusan.RSTableMetro();
        rSButtonIcon_new2 = new newscomponents.RSButtonIcon_new();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        rSButtonIcon_new1.setBackground(new java.awt.Color(181, 35, 54));
        rSButtonIcon_new1.setText("IMPORTAR A ACCESS");
        rSButtonIcon_new1.setBackgroundHover(new java.awt.Color(255, 0, 0));
        rSButtonIcon_new1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        rSButtonIcon_new1.setForegroundHover(new java.awt.Color(0, 0, 0));
        rSButtonIcon_new1.setForegroundIconHover(new java.awt.Color(0, 0, 0));
        rSButtonIcon_new1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FOLDER);
        rSButtonIcon_new1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIcon_new1ActionPerformed(evt);
            }
        });
        rSButtonIcon_new1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rSButtonIcon_new1KeyPressed(evt);
            }
        });

        Mensaje.setForeground(new java.awt.Color(0, 255, 51));
        Mensaje.setText("REALIZANDO IMPORTACIÓN....");

        PanelTabla.setBackground(new java.awt.Color(0, 0, 0));

        TablaExcel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaExcel.setColorBackgoundHead(new java.awt.Color(Parameters.ColorApp1, Parameters.ColorApp2, Parameters.ColorApp3));
        TablaExcel.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        TablaExcel.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        TablaExcel.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        TablaExcel.setColorSelBackgound(new java.awt.Color(0, 0, 0));
        TablaExcel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        TablaExcel.setFuenteFilas(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        TablaExcel.setFuenteFilasSelect(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        TablaExcel.setFuenteHead(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        TablaExcel.setRowHeight(25);
        jScrollPane2.setViewportView(TablaExcel);

        javax.swing.GroupLayout PanelTablaLayout = new javax.swing.GroupLayout(PanelTabla);
        PanelTabla.setLayout(PanelTablaLayout);
        PanelTablaLayout.setHorizontalGroup(
            PanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(PanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelTablaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        PanelTablaLayout.setVerticalGroup(
            PanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 195, Short.MAX_VALUE)
            .addGroup(PanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelTablaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        rSButtonIcon_new2.setBackground(new java.awt.Color(Parameters.ColorApp1, Parameters.ColorApp2, Parameters.ColorApp3));
        rSButtonIcon_new2.setText("RESET APP");
        rSButtonIcon_new2.setBackgroundHover(new java.awt.Color(255, 0, 0));
        rSButtonIcon_new2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        rSButtonIcon_new2.setForegroundHover(new java.awt.Color(0, 0, 0));
        rSButtonIcon_new2.setForegroundIconHover(new java.awt.Color(0, 0, 0));
        rSButtonIcon_new2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SETTINGS);
        rSButtonIcon_new2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIcon_new2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rSButtonIcon_new1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                .addGap(6, 6, 6)
                                .addComponent(rSButtonIcon_new2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addComponent(Mensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSButtonIcon_new1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonIcon_new2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(PanelTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(Mensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        setSize(new java.awt.Dimension(558, 317));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonIcon_new1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIcon_new1ActionPerformed
        selecArchivo.setName("CEROTE");
        int Dialogo = selecArchivo.showDialog(null, "SELECCIONA ARCHIVO");
        if (Dialogo == JFileChooser.APPROVE_OPTION) {
            Windows.Settings.setSize(600, 300);
            PanelTabla.setVisible(true);
            this.Mensaje.setVisible(true);
            archivo = selecArchivo.getSelectedFile();
            if (archivo.getName().endsWith("xls") || archivo.getName().endsWith("xlsx")) {
                try {
                    this.Mensaje.setText("REALIZANDO IMPORTACIÓN....");
                    Thread.sleep(1000);
                    boolean res = Objects.Methods.Importar(archivo, TablaExcel);
                    if (res == true) {
                        this.Mensaje.setText("SINCRONIZANDO CON BASE DE DATOS...");
                        Thread.sleep(1000);
                        Objects.Methods.SyncExcel(TablaExcel);
                        this.Mensaje.setText("IMPORTACIÓN EXITOSA!!");
                    }
                    if (res == false) {
                        this.Mensaje.setText("FALLO AL INSERTAR REGISTROS");
                        Thread.sleep(2000);
                        this.Mensaje.setText("REVISAR LOG!");

                    }
                } catch (Exception e) {
                    System.out.println("se metio al catch");
                }

            } else {
                JOptionPane.showMessageDialog(null, "Elija un formato valido.");
            }
        }
        if (Dialogo == JFileChooser.CANCEL_OPTION) {
            PanelTabla.setVisible(false);
            this.Mensaje.setVisible(false);
        }

    }//GEN-LAST:event_rSButtonIcon_new1ActionPerformed

    private void rSButtonIcon_new2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIcon_new2ActionPerformed

        if(JOptionPane.showConfirmDialog(null, "¿DESEAS HACER RESET A LA APP?")==0){
            new Parameters().ParametrosDefault();
        }
    }//GEN-LAST:event_rSButtonIcon_new2ActionPerformed

    private void rSButtonIcon_new1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rSButtonIcon_new1KeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
        this.setVisible(false);
        IMPRESORA.scanner.requestFocus();
        }
    }//GEN-LAST:event_rSButtonIcon_new1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Settings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Mensaje;
    public static javax.swing.JPanel PanelTabla;
    public static rojerusan.RSTableMetro TablaExcel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private newscomponents.RSButtonIcon_new rSButtonIcon_new1;
    private newscomponents.RSButtonIcon_new rSButtonIcon_new2;
    // End of variables declaration//GEN-END:variables
}
